# A simple Makefile
# # Saad Arshad 00857432
# # CS 262, Lab Section 208
# # Lab 7

CC = gcc
CFLAGS = -g -Wall -pedantic-errors

TARGET1 = AsciiToBinary
TARGET2 = BinaryToAscii

all: $(TARGET1) $(TARGET2)

$(TARGET1):
	$(CC) $(CFLAGS) -o $(TARGET1) $(TARGET1).c

$(TARGETS2):
	$(CC) $(CFLAGS) -o $(TARGET2) $(TARGET2).c

clean:
	rm $(TARGET1)
	rm $(TARGET2)
