# A simple Makefile
# # <Your Name and G Number>
# # CS 262, Lab Section <Lab Section Number>
# # Lab 1

all: lab1_sarshad4_208.c
	gcc -g -Wall -o lab1_sarshad4_208 lab1_sarshad4_208.c

clean:
	rm lab1_sarshad4_208
