# A simple Makefile
# # Saad Arshad 00857432
# # CS 262, Lab Section 208
# # Lab 10

CC = gcc
CFLAGS = -g -Wall -pedantic-errors

TARGET1 = lab10

all: $(TARGET1)

$(TARGET1):
	$(CC) $(CFLAGS) -o $(TARGET1) $(TARGET1).c

clean:
	rm $(TARGET1)

